[Service]
  Host = "edgex-device-grove"
  ServerBindAddr = '0.0.0.0'
  Port = 49992
  ConnectRetries = 3
  HealthCheck = ""
  StartupMsg = "device Grove PI started"
  ReadMaxLimit = 256
  Timeout = 5000
  CheckInterval = '10s'

[Clients]
  [Clients.Data]
    Host = "edgex-core-data"
    Port = 48080

  [Clients.Metadata]
    Host = "edgex-core-metadata"
    Port = 48081

[Device]
  DataTransform = true
  Discovery = false
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  SendReadingsOnChanged = true

[Driver]
  BME680_Temp_Offset = -1.0

[Logging]
  RemoteURL = ""
  File = "-"

[[DeviceList]]
  Name = "GroveDevice"
  Profile = "Grove_Device"
  Description = "Grove Device to Read/Write sensors connected to GrovePI"
  Labels = [ "Grove LED, Grove Button, Grove Buzzer, Grove LCD, Grove LightSensor, Grove Relay, Grove RotarySensor, Grove SoundSensor, Grove BME680Sensor" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = "/api/v1/device/GroveDevice"
  [[DeviceList.AutoEvents]]
    Resource = "Get_RotarySensorMeasurements"
    OnChange = false
    Frequency = "2s"
  [[DeviceList.AutoEvents]]
    Resource = "Get_LightIntensity"
    OnChange = false
    Frequency = "2s"
   [[DeviceList.AutoEvents]]
    Resource = "Get_SoundIntensity"
    OnChange = false
    Frequency = "2s"
